import type { Page, Product } from '@/payload-types'

/** Lexical rich text shape generated by Payload (pages hero is the canonical reference). */
export type PayloadRichText = NonNullable<Page['hero']['richText']>

export type PayloadRichTextChild = PayloadRichText['root']['children'][number]

export type ProductRichText = NonNullable<Product['description']>

export function isPayloadRichText(value: unknown): value is PayloadRichText {
  return (
    typeof value === 'object' &&
    value !== null &&
    'root' in value &&
    typeof (value as PayloadRichText).root === 'object' &&
    (value as PayloadRichText).root !== null
  )
}
