/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    categories: Category;
    media: Media;
    reviews: Review;
    'site-review-submissions': SiteReviewSubmission;
    forms: Form;
    'form-submissions': FormSubmission;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      orders: 'orders';
      cart: 'carts';
      addresses: 'addresses';
    };
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'site-review-submissions': SiteReviewSubmissionsSelect<false> | SiteReviewSubmissionsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  internalToken?: string | null;
  roles?: ('admin' | 'customer')[] | null;
  orders?: {
    docs?: (string | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  cart?: {
    docs?: (string | Cart)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  addresses?: {
    docs?: (string | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    name?: string | null;
    phone?: string | null;
    alternatePhone?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  customer?: (string | null) | User;
  customerEmail?: string | null;
  transactions?: (string | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'INR' | null;
  customerName?: string | null;
  /**
   * Product titles for this order (auto-filled from line items).
   */
  productNames?: string | null;
  customerPhone?: string | null;
  accessToken?: string | null;
  /**
   * Select a product to fetch variant options
   */
  adminProduct?: (string | null) | Product;
  /**
   * Select a variant of the chosen product
   */
  adminVariant?: (string | null) | Variant;
  adminQuantity?: number | null;
  /**
   * Select from available customer addresses
   */
  adminAddress?: (string | null) | Address;
  /**
   * Pending for COD until collected on delivery; mark Paid when cash is received.
   */
  paymentStatus?: ('pending' | 'paid' | 'failed') | null;
  /**
   * Shipping fee charged for this order (₹0 = free shipping).
   */
  shippingCharge?: number | null;
  emailSent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: string | Media;
        variantOption?: (string | null) | VariantOption;
        id?: string | null;
      }[]
    | null;
  layout?: (CallToActionBlock | ContentBlock | MediaBlock)[] | null;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (string | VariantType)[] | null;
  variants?: {
    docs?: (string | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInINREnabled?: boolean | null;
  priceInINR?: number | null;
  /**
   * Original MRP. Shown struck through on product cards when higher than the sale price.
   */
  compareAtPriceInINR?: number | null;
  relatedProducts?: (string | Product)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  categories?: (string | Category)[] | null;
  /**
   * Sell unit for voice cart (pack, kg, litre, dozen, …)
   */
  unit?: string | null;
  /**
   * Speech aliases for Naradji STT matching (Hinglish / Hindi / Gujarati)
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: string;
  _variantOptions_options_order?: string | null;
  variantType: string | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: string;
  label: string;
  name: string;
  options?: {
    docs?: (string | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'products';
                value: string | Product;
              } | null)
            | ({
                relationTo: 'categories';
                value: string | Category;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  publishedOn?: string | null;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Makes the hero image area clickable. If empty, the first visible link below is used.
     */
    clickLink?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'products';
            value: string | Product;
          } | null)
        | ({
            relationTo: 'categories';
            value: string | Category;
          } | null);
      url?: string | null;
    };
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'products';
                  value: string | Product;
                } | null)
              | ({
                  relationTo: 'categories';
                  value: string | Category;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * Shown on tablet and desktop (md breakpoint and up).
     */
    media?: (string | null) | Media;
    /**
     * Optional. Shown on small screens. Falls back to the desktop image when empty.
     */
    mobileMedia?: (string | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | CTABannerBlock
    | CategoryCardsBlock
    | CollectionGridBlock
    | CompetitionFlowBlock
    | ContentBlock
    | DisciplineArchiveBlock
    | DividerBlock
    | FAQBlock
    | FeatureBlock
    | HighlightCardsBlock
    | InstagramReelsBlock
    | MediaBlock
    | ArchiveBlock
    | AppleCardsCarouselBlock
    | CarouselBlock
    | ThreeItemGridBlock
    | BannerBlock
    | CodeBlock
    | FormBlock
    | ReviewsBlock
    | VideosBlock
    | TestimonialsBlock
    | TextBlock
    | UpcommingEvents
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABannerBlock".
 */
export interface CTABannerBlock {
  icon?: ('sparkles' | 'gift' | 'truck' | 'heart' | 'none') | null;
  headline: string;
  subtext?: string | null;
  link: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'products';
          value: string | Product;
        } | null)
      | ({
          relationTo: 'categories';
          value: string | Category;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
  };
  variant?: ('primary' | 'muted' | 'card') | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryCardsBlock".
 */
export interface CategoryCardsBlock {
  title: string;
  categories: (string | Category)[];
  columns?: ('2' | '3') | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'categoryCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CollectionGridBlock".
 */
export interface CollectionGridBlock {
  headline?: string | null;
  subtext?: string | null;
  items?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'collectionGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CompetitionFlowBlock".
 */
export interface CompetitionFlowBlock {
  heading?: string | null;
  subtitle?: string | null;
  /**
   * Optional embed URL. If set, cards are hidden.
   */
  videoUrl?: string | null;
  cards?:
    | {
        title: string;
        description?: string | null;
        /**
         * Shown on tablet and desktop (md breakpoint and up).
         */
        image?: (string | null) | Media;
        /**
         * Optional. Shown on small screens. Falls back to the desktop image when empty.
         */
        mobileImage?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'competitionFlow';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'products';
                value: string | Product;
              } | null)
            | ({
                relationTo: 'categories';
                value: string | Category;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DisciplineArchiveBlock".
 */
export interface DisciplineArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  limit?: number | null;
  showOutOfStock?: boolean | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'disciplineArchive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlock".
 */
export interface DividerBlock {
  style?: ('line' | 'dots' | 'space') | null;
  width?: ('full' | 'container' | 'narrow') | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'divider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  headline?: string | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  items: {
    question: string;
    answer: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureBlock".
 */
export interface FeatureBlock {
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown on tablet and desktop (md breakpoint and up).
   */
  media: string | Media;
  /**
   * Optional. Shown on small screens. Falls back to the desktop image when empty.
   */
  mobileMedia?: (string | null) | Media;
  enableLink?: boolean | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'products';
          value: string | Product;
        } | null)
      | ({
          relationTo: 'categories';
          value: string | Category;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
  };
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  imagePosition?: ('left' | 'right' | 'top' | 'bottom') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'feature';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HighlightCardsBlock".
 */
export interface HighlightCardsBlock {
  headline?: string | null;
  cards?:
    | {
        title: string;
        description?: string | null;
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'products';
                value: string | Product;
              } | null)
            | ({
                relationTo: 'categories';
                value: string | Category;
              } | null);
          url?: string | null;
          label: string;
        };
        /**
         * Shown on tablet and desktop (md breakpoint and up).
         */
        image?: (string | null) | Media;
        /**
         * Optional. Shown on small screens. Falls back to the desktop image when empty.
         */
        mobileImage?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'highlightCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InstagramReelsBlock".
 */
export interface InstagramReelsBlock {
  headline?: string | null;
  posts?:
    | {
        /**
         * Full Instagram post or reel URL (e.g. https://www.instagram.com/p/...)
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'instagramReels';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  /**
   * Shown on tablet and desktop (md breakpoint and up).
   */
  media: string | Media;
  /**
   * Optional. Shown on small screens. Falls back to the desktop image when empty.
   */
  mobileMedia?: (string | null) | Media;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  imagePosition?: ('left' | 'right' | 'top' | 'bottom') | null;
  mobileImagePosition?: ('top' | 'bottom' | 'hidden') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AppleCardsCarouselBlock".
 */
export interface AppleCardsCarouselBlock {
  heading?: string | null;
  cards: {
    category: string;
    title: string;
    /**
     * Shown on tablet and desktop (md breakpoint and up).
     */
    image: string | Media;
    /**
     * Optional. Shown on small screens. Falls back to the desktop image when empty.
     */
    mobileImage?: (string | null) | Media;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    id?: string | null;
  }[];
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'appleCardsCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  heading?: string | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocsTotal?: number | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock".
 */
export interface ThreeItemGridBlock {
  heading?: string | null;
  products?: (string | Product)[] | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeItemGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success' | 'emphasis';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewsBlock".
 */
export interface ReviewsBlock {
  headline?: string | null;
  reviews?:
    | {
        author: string;
        text: string;
        rating: number;
        avatar?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'reviews';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideosBlock".
 */
export interface VideosBlock {
  headline?: string | null;
  videos?:
    | {
        video: string | Media;
        caption?: string | null;
        buttonLabel?: string | null;
        buttonLinkType?: ('reference' | 'custom') | null;
        buttonReference?:
          | ({
              relationTo: 'pages';
              value: string | Page;
            } | null)
          | ({
              relationTo: 'products';
              value: string | Product;
            } | null)
          | ({
              relationTo: 'categories';
              value: string | Category;
            } | null);
        buttonUrl?: string | null;
        buttonNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  headline?: string | null;
  testimonials?:
    | {
        quote: string;
        author: string;
        location?: string | null;
        avatar?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UpcommingEvents".
 */
export interface UpcommingEvents {
  title?: string | null;
  mobileLayout?: ('default' | 'compact' | 'hideMobile' | 'hideDesktop') | null;
  mobileColumns?: ('1' | '2') | null;
  desktopColumns?: ('auto' | '1' | '2' | '3' | '4' | '6') | null;
  textAlign?: ('auto' | 'left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'upcommingEvents';
}
/**
 * Each variant must be Published with price and inventory set. Draft variants are hidden on the storefront.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: string;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: string | Product;
  options: (string | VariantOption)[];
  inventory?: number | null;
  priceInINREnabled?: boolean | null;
  priceInINR?: number | null;
  /**
   * Original MRP for this variant. Shown struck through on the storefront when higher than the sale price.
   */
  compareAtPriceInINR?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: 'cod' | null;
  cod?: {
    reference?: string | null;
  };
  billingAddress?: {
    name?: string | null;
    phone?: string | null;
    alternatePhone?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (string | null) | User;
  customerEmail?: string | null;
  order?: (string | null) | Order;
  cart?: (string | null) | Cart;
  amount?: number | null;
  currency?: 'INR' | null;
  /**
   * Shipping fee included in this payment (₹0 = free shipping).
   */
  shippingCharge?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (string | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'INR' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: string;
  customer?: (string | null) | User;
  name?: string | null;
  phone?: string | null;
  alternatePhone?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country: 'IN';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  product: string | Product;
  user: string | User;
  rating: number;
  reviewText?: string | null;
  photos?: (string | Media)[] | null;
  videos?: (string | Media)[] | null;
  status: 'pending' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * Homepage review submissions from the storefront carousel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-review-submissions".
 */
export interface SiteReviewSubmission {
  id: string;
  author: string;
  text: string;
  rating: number;
  status: 'pending' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'site-review-submissions';
        value: string | SiteReviewSubmission;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'addresses';
        value: string | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: string | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: string | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: string | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: string | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  internalToken?: T;
  roles?: T;
  orders?: T;
  cart?: T;
  addresses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        clickLink?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
        mobileMedia?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        ctaBanner?: T | CTABannerBlockSelect<T>;
        categoryCards?: T | CategoryCardsBlockSelect<T>;
        collectionGrid?: T | CollectionGridBlockSelect<T>;
        competitionFlow?: T | CompetitionFlowBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        disciplineArchive?: T | DisciplineArchiveBlockSelect<T>;
        divider?: T | DividerBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        feature?: T | FeatureBlockSelect<T>;
        highlightCards?: T | HighlightCardsBlockSelect<T>;
        instagramReels?: T | InstagramReelsBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        appleCardsCarousel?: T | AppleCardsCarouselBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        reviews?: T | ReviewsBlockSelect<T>;
        videos?: T | VideosBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        text?: T | TextBlockSelect<T>;
        upcommingEvents?: T | UpcommingEventsSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABannerBlock_select".
 */
export interface CTABannerBlockSelect<T extends boolean = true> {
  icon?: T;
  headline?: T;
  subtext?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  variant?: T;
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryCardsBlock_select".
 */
export interface CategoryCardsBlockSelect<T extends boolean = true> {
  title?: T;
  categories?: T;
  columns?: T;
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CollectionGridBlock_select".
 */
export interface CollectionGridBlockSelect<T extends boolean = true> {
  headline?: T;
  subtext?: T;
  items?:
    | T
    | {
        label?: T;
        id?: T;
      };
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CompetitionFlowBlock_select".
 */
export interface CompetitionFlowBlockSelect<T extends boolean = true> {
  heading?: T;
  subtitle?: T;
  videoUrl?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        mobileImage?: T;
        id?: T;
      };
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DisciplineArchiveBlock_select".
 */
export interface DisciplineArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  limit?: T;
  showOutOfStock?: T;
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlock_select".
 */
export interface DividerBlockSelect<T extends boolean = true> {
  style?: T;
  width?: T;
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  headline?: T;
  introContent?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureBlock_select".
 */
export interface FeatureBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  media?: T;
  mobileMedia?: T;
  enableLink?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  imagePosition?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HighlightCardsBlock_select".
 */
export interface HighlightCardsBlockSelect<T extends boolean = true> {
  headline?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        image?: T;
        mobileImage?: T;
        id?: T;
      };
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InstagramReelsBlock_select".
 */
export interface InstagramReelsBlockSelect<T extends boolean = true> {
  headline?: T;
  posts?:
    | T
    | {
        url?: T;
        id?: T;
      };
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  mobileMedia?: T;
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  imagePosition?: T;
  mobileImagePosition?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AppleCardsCarouselBlock_select".
 */
export interface AppleCardsCarouselBlockSelect<T extends boolean = true> {
  heading?: T;
  cards?:
    | T
    | {
        category?: T;
        title?: T;
        image?: T;
        mobileImage?: T;
        content?: T;
        id?: T;
      };
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  heading?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  populatedDocs?: T;
  populatedDocsTotal?: T;
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock_select".
 */
export interface ThreeItemGridBlockSelect<T extends boolean = true> {
  heading?: T;
  products?: T;
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock_select".
 */
export interface CodeBlockSelect<T extends boolean = true> {
  language?: T;
  code?: T;
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewsBlock_select".
 */
export interface ReviewsBlockSelect<T extends boolean = true> {
  headline?: T;
  reviews?:
    | T
    | {
        author?: T;
        text?: T;
        rating?: T;
        avatar?: T;
        id?: T;
      };
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideosBlock_select".
 */
export interface VideosBlockSelect<T extends boolean = true> {
  headline?: T;
  videos?:
    | T
    | {
        video?: T;
        caption?: T;
        buttonLabel?: T;
        buttonLinkType?: T;
        buttonReference?: T;
        buttonUrl?: T;
        buttonNewTab?: T;
        id?: T;
      };
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  headline?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        author?: T;
        location?: T;
        avatar?: T;
        id?: T;
      };
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  content?: T;
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UpcommingEvents_select".
 */
export interface UpcommingEventsSelect<T extends boolean = true> {
  title?: T;
  mobileLayout?: T;
  mobileColumns?: T;
  desktopColumns?: T;
  textAlign?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  user?: T;
  rating?: T;
  reviewText?: T;
  photos?: T;
  videos?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-review-submissions_select".
 */
export interface SiteReviewSubmissionsSelect<T extends boolean = true> {
  author?: T;
  text?: T;
  rating?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  name?: T;
  phone?: T;
  alternatePhone?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInINREnabled?: T;
  priceInINR?: T;
  compareAtPriceInINR?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        variantOption?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInINREnabled?: T;
  priceInINR?: T;
  compareAtPriceInINR?: T;
  relatedProducts?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  categories?: T;
  unit?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        name?: T;
        phone?: T;
        alternatePhone?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  customerName?: T;
  productNames?: T;
  customerPhone?: T;
  accessToken?: T;
  adminProduct?: T;
  adminVariant?: T;
  adminQuantity?: T;
  adminAddress?: T;
  paymentStatus?: T;
  shippingCharge?: T;
  emailSent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  paymentMethod?: T;
  cod?:
    | T
    | {
        reference?: T;
      };
  billingAddress?:
    | T
    | {
        name?: T;
        phone?: T;
        alternatePhone?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  shippingCharge?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    link?: string | null;
  };
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'products';
                value: string | Product;
              } | null)
            | ({
                relationTo: 'categories';
                value: string | Category;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  footerCopy?: string | null;
  sections?:
    | {
        heading: string;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'products';
                      value: string | Product;
                    } | null)
                  | ({
                      relationTo: 'categories';
                      value: string | Category;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'instagram' | 'x' | 'linkedin' | 'youtube' | 'facebook' | 'pinterest';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?: T;
      };
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  footerCopy?: T;
  sections?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}